import React, { createContext, useState } from "react";
import AlabamaShape from "../assets/US_States_Imgs/alabama.png";
import FloridaShape from "../assets/US_States_Imgs/florida.png";
// import IndianaShape from "../assets/US_States_Imgs/indiana.png";
// import KansasShape from "../assets/US_States_Imgs/kansas.png";
// import KentuckyShape from "../assets/US_States_Imgs/kentucky.png";
import MarylandShape from "../assets/US_States_Imgs/maryland.png";
import MassachusettsShape from "../assets/US_States_Imgs/massachusetts.png";
import MichiganShape from "../assets/US_States_Imgs/michigan.png";
import NewYorkShape from "../assets/US_States_Imgs/newyork.png";
import NorthCarolinaShape from "../assets/US_States_Imgs/northcarolina.png";
import NorthDakotaShape from "../assets/US_States_Imgs/northdakota.png";
// import OhioShape from "../assets/US_States_Imgs/ohio.png";
import OregonShape from "../assets/US_States_Imgs/oregon.png";
// import PennsylvaniaShape from "../assets/US_States_Imgs/pennsylvania.png";
// import TexasShape from "../assets/US_States_Imgs/texas.png";
// import WashingtonShape from "../assets/US_States_Imgs/washington.png";
import WestVirginiaShape from "../assets/US_States_Imgs/westvirginia.png";

export const CommunityContext = createContext();

const CommunityContextProvider = (props) => {
  const [communityStates] = useState([
    {
      state: "Alabama",
      usStateId: "alabama",
      stateAbbr: "AL",
      stateBgURL: AlabamaShape,
      communities: [
        {
          communityName: "Wolf Bay",
          communityCity: "Elberta, AL",
          communityAddress: "9741 Wilson Rd, Elberta, AL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "wolfbay",
          communityID: "AL-1",
        },
      ],
    },
    {
      state: "Florida",
      usStateId: "florida",
      stateAbbr: "FL",
      stateBgURL: FloridaShape,
      communities: [
        {
          communityName: "Applegate",
          communityCity: "Deland, FL",
          communityAddress: "399 Circle Dr, Deland, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "applegate",
          communityID: "FL-1",
        },
        {
          communityName: "Bay Oaks Village I",
          communityCity: "Panama City, FL",
          communityAddress: "409 School Ave, Panama City, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "bayoaksvillage",
          communityID: "FL-2",
        },
        {
          communityName: "Bay Oaks Village I",
          communityCity: "Panama City, FL",
          communityAddress: "420 N Kimbrel Ave, Panama City, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "bayoaksvillage",
          communityID: "FL-3",
        },
        {
          communityName: "Congress MHP",
          communityCity: "West Palm Beach, FL",
          communityAddress: "1960 Congress Avenue, West Palm Beach, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "congress",
          communityID: "FL-4",
        },
        {
          communityName: "Everglades MHP",
          communityCity: "Clewiston, FL",
          communityAddress: "500 S Francisco Street Clewiston, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "everglades",
          communityID: "FL-5",
        },
        {
          communityName: "Gulf Breeze",
          communityCity: "Hudson, FL",
          communityAddress: "7530 Maryland Ave, Hudson, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "gulfbreeze",
          communityID: "FL-6",
        },
        {
          communityName: "Hunter Springs",
          communityCity: "Crystal River, FL",
          communityAddress: "316 NE 2nd Street, Crystal River, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "huntersprings",
          communityID: "FL-7",
        },
        {
          communityName: "J Bar J Estates",
          communityCity: "Miami, FL",
          communityAddress: "2980 NW 79th St, Miami, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "jbarjestates",
          communityID: "FL-8",
        },
        {
          communityName: "Lake Saunders MHC",
          communityCity: "Miami, FL",
          communityAddress: "2980 NW 79th St, Miami, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "lakesaunders",
          communityID: "FL-9",
        },
        {
          communityName: "Lake Wales MHC",
          communityCity: "Lake Wales, FL",
          communityAddress: "705 N. Scenic Highway, Lake Wales, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "lakewales",
          communityID: "FL-10",
        },
        {
          communityName: "Oceanaire",
          communityCity: "New Smyrna Beach, FL",
          communityAddress: "1311 Turnbull Street, New Smyrna Beach, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "oceanaire",
          communityID: "FL-11",
        },
        {
          communityName: "Ormond Beach Oasis",
          communityCity: "Ormond Beach, FL",
          communityAddress: "955 S. Nova Rd",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "ormondbeachoasis",
          communityID: "FL-12",
        },
        {
          communityName: "Palm Spring Estates",
          communityCity: "Tarpon Springs, FL",
          communityAddress: "40110 US 19 N, Tarpon Springs, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "palmspringestates",
          communityID: "FL-13",
        },
        {
          communityName: "Royal Oaks MHC",
          communityCity: "Vero Beach, FL",
          communityAddress: "8125 US 1 Highway, Vero Beach, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "royaloaks",
          communityID: "FL-14",
        },
        {
          communityName: "Shady Oaks",
          communityCity: "Miami, FL",
          communityAddress: "14701 NE 6 Avenue, Miami, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "shadyoaks",
          communityID: "FL-15",
        },
        {
          communityName: "Town & Country MHC",
          communityCity: "Jacksonville, FL",
          communityAddress: "7835 Morse Avenue, Jacksonville, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "townandcountry",
          communityID: "FL-16",
        },
        {
          communityName: "Tradewinds",
          communityCity: "Cocoa, FL",
          communityAddress: "4100 N Cocoa Blvd, Cocoa, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "tradewinds",
          communityID: "FL-17",
        },
        {
          communityName: "Westwood MHC",
          communityCity: "Ormond Beach, FL",
          communityAddress: "1804 Nelson Av, Ormond Beach, FL",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "westwood",
          communityID: "FL-18",
        },
      ],
    },
    // {
    //   state: "Indiana",
    //   usStateId: "indiana",
    //   stateAbbr: "IN",
    //   stateBgURL: IndianaShape,
    //   communities: [
    //     {
    //       communityName: "Moores Hill MHP",
    //       communityCity: "Aurora, IN",
    //       communityAddress: "Address",
    //       communityType: "All Ages",
    //       communityAmenities: "Amenities",
    //       communityURL: "mooreshill",
    //       communityID: "IN-1",
    //     },
    //   ],
    // },
    // {
    //   state: "Kansas",
    //   usStateId: "kansas",
    //   stateAbbr: "KS",
    //   stateBgURL: KansasShape,
    //   communities: [
    //     {
    //       communityName: "Cherrywoods MHP",
    //       communityCity: "Ottawa, KS",
    //       communityAddress: "Address",
    //       communityType: "All Ages",
    //       communityAmenities: "Amenities",
    //       communityURL: "cherrywoods",
    //       communityID: "KS-1",
    //     },
    //     {
    //       communityName: "Fishin' MHP",
    //       communityCity: "Wichita, KS",
    //       communityAddress: "Address",
    //       communityType: "All Ages",
    //       communityAmenities: "Amenities",
    //       communityURL: "fishin",
    //       communityID: "KS-2",
    //     },
    //   ],
    // },
    // {
    //   state: "Kentucky",
    //   usStateId: "kentucky",
    //   stateAbbr: "KY",
    //   stateBgURL: KentuckyShape,
    //   communities: [
    //     {
    //       communityName: "Ponderosa MHP",
    //       communityCity: "Elizabethtown, KY",
    //       communityAddress: "Address",
    //       communityType: "All Ages",
    //       communityAmenities: "Amenities",
    //       communityURL: "ponderosa",
    //       communityID: "KY-1",
    //     },
    //   ],
    // },
    {
      state: "Maryland",
      usStateId: "maryland",
      stateAbbr: "MD",
      stateBgURL: MarylandShape,
      communities: [
        {
          communityName: "Mobile Manor",
          communityCity: "Rosedale, MD",
          communityAddress: "1302 Evering Ave, Rosedale, MD",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "mobilemanor",
          communityID: "MD-1",
        },
        // {
        //   communityName: "Rio Vista MHP",
        //   communityCity: "Lothian, MD",
        //   communityAddress: "Address",
        //   communityType: "All Ages",
        //   communityAmenities: "Amenities",
        //   communityURL: "riovista",
        //   communityID: "MD-2",
        // },
        {
          communityName: "Royal Palm Trailer Park",
          communityCity: "Potomac, MD",
          communityAddress: "10221 River Road #59831, Potomac, MD",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "royalpalm",
          communityID: "MD-3",
        },
      ],
    },
    {
      state: "Massachusettes",
      usStateId: "massachusettes",
      stateAbbr: "MA",
      stateBgURL: MassachusettsShape,
      communities: [
        {
          communityName: "Mayflower Hills MHC",
          communityCity: "Plymouth, MA",
          communityAddress: "0 Minuteman Lane, Plymouth, MA",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "mayflowerhills",
          communityID: "MA-1",
        },
      ],
    },
    {
      state: "Michigan",
      usStateId: "michigan",
      stateAbbr: "MI",
      stateBgURL: MichiganShape,
      communities: [
        {
          communityName: "Lamberton Lake MHC",
          communityCity: "Grand Rapids, MI",
          communityAddress: "1561 Sherin Drive NE, Grand Rapids,",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "lambertonlake",
          communityID: "MI-1",
        },
        // {
        //   communityName: "Victoria Woods MHC",
        //   communityCity: "Midland, MI",
        //   communityAddress: "Address",
        //   communityType: "All Ages",
        //   communityAmenities: "Amenities",
        //   communityURL: "victoriawoods",
        //   communityID: "MI-2",
        // },
        // {
        //   communityName: "Kimball Estates",
        //   communityCity: "Kimball, MI",
        //   communityAddress: "Address",
        //   communityType: "All Ages",
        //   communityAmenities: "Amenities",
        //   communityURL: "kimballestates",
        //   communityID: "MI-3",
        // },
      ],
    },
    {
      state: "New York",
      usStateId: "newyork",
      stateAbbr: "NY",
      stateBgURL: NewYorkShape,
      communities: [
        {
          communityName: "Collins MHC",
          communityCity: "Plattsburgh, NY",
          communityAddress: "53 Mill Lane, Plattsburgh, NY",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "collins",
          communityID: "NY-1",
        },
        {
          communityName: "Underwood Estates",
          communityCity: "Plattsburgh, NY",
          communityAddress: "53 Mill Lane, Plattsburgh, NY",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "underwoodestates",
          communityID: "NY-2",
        },
      ],
    },
    {
      state: "North Carolina",
      usStateId: "northcarolina",
      stateAbbr: "NC",
      stateBgURL: NorthCarolinaShape,
      communities: [
        {
          communityName: "Cedar Grove MHC",
          communityCity: "Kernersville, NC",
          communityAddress: "209 Pegg Farm Lane, Kernersville, NC",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "cedargrove",
          communityID: "NC-1",
        },
        {
          communityName: "Colonial MHC",
          communityCity: "New Bern, NC",
          communityAddress: "76 Morningstar Drive, New Bern, NC",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "colonial",
          communityID: "NC-2",
        },
        {
          communityName: "Lambeth MHC",
          communityCity: "Winston-Salem, NC",
          communityAddress: "4630 South Main Street, Winston-Salem, NC",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "lambeth",
          communityID: "NC-3",
        },
        {
          communityName: "Parkwood MHC",
          communityCity: "Winston-Salem, NC",
          communityAddress: "338 Barnes Road Lot 100, Winston-Salem, NC",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "parkwood",
          communityID: "NC-4",
        },
        {
          communityName: "Vandemere MHC",
          communityCity: "Greenville, NC",
          communityAddress: "474 Earl Road, Greenville, NC",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "vandemere",
          communityID: "NC-5",
        },
      ],
    },
    {
      state: "North Dakota",
      usStateId: "northdakota",
      stateAbbr: "ND",
      stateBgURL: NorthDakotaShape,
      communities: [
        {
          communityName: "Apple Creek",
          communityCity: "Bismarck, ND",
          communityAddress: "111 Albatross Drive, Bismarck, ND",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "applecreek",
          communityID: "ND-1",
        },
        {
          communityName: "Countryside",
          communityCity: "Mandan, ND",
          communityAddress: "103 Countryside Lane, Mandan, ND",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "countryside",
          communityID: "ND-2",
        },
        {
          communityName: "Parktown",
          communityCity: "Mandan, ND",
          communityAddress: "703 6th Ave SE, Mandan, ND",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "parktown",
          communityID: "ND-3",
        },
      ],
    },
    // {
    //   state: "Ohio",
    //   usStateId: "ohio",
    //   stateAbbr: "OH",
    //   stateBgURL: OhioShape,
    //   communities: [
    //     {
    //       communityName: "Northgate MHP",
    //       communityCity: "Mt Gilead, OH",
    //       communityAddress: "Address",
    //       communityType: "All Ages",
    //       communityAmenities: "Amenities",
    //       communityURL: "northgate",
    //       communityID: "OH-1",
    //     },
    //   ],
    // },
    {
      state: "Oregon",
      usStateId: "oregon",
      stateAbbr: "OR",
      stateBgURL: OregonShape,
      communities: [
        // {
        //   communityName: "Shasta Glen MHC",
        //   communityCity: "Klamath Falls, OR",
        //   communityAddress: "Address",
        //   communityType: "All Ages",
        //   communityAmenities: "Amenities",
        //   communityURL: "shastaglen",
        //   communityID: "OR-1",
        // },
        {
          communityName: "Valley View",
          communityCity: "Roseburg, OR",
          communityAddress: "200 Emils Way, Roseburg, OR",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "valleyview",
          communityID: "OR-2",
        },
      ],
    },
    // {
    //   state: "Pennsylvania",
    //   usStateId: "pennsylvania",
    //   stateAbbr: "PA",
    //   stateBgURL: PennsylvaniaShape,
    //   communities: [
    //     {
    //       communityName: "Tracey Acres MHP",
    //       communityCity: "Erie, PA",
    //       communityAddress: "Address",
    //       communityType: "All Ages",
    //       communityAmenities: "Amenities",
    //       communityURL: "traceyacres",
    //       communityID: "PA-1",
    //     },
    //     {
    //       communityName: "Tri-State MHP",
    //       communityCity: "Erie, PA",
    //       communityAddress: "Address",
    //       communityType: "All Ages",
    //       communityAmenities: "Amenities",
    //       communityURL: "tristatemhp",
    //       communityID: "PA-2",
    //     },
    //   ],
    // },
    // {
    //   state: "Texas",
    //   usStateId: "texas",
    //   stateAbbr: "TX",
    //   stateBgURL: TexasShape,
    //   communities: [
    //     {
    //       communityName: "Knollwood Village",
    //       communityCity: "Knollwood, TX",
    //       communityAddress: "Address",
    //       communityType: "All Ages",
    //       communityAmenities: "Amenities",
    //       communityURL: "knollwood",
    //       communityID: "TX-1",
    //     },
    //   ],
    // },
    // {
    //   state: "Washington",
    //   usStateId: "washington",
    //   stateAbbr: "WA",
    //   stateBgURL: WashingtonShape,
    //   communities: [
    //     {
    //       communityName: "University MHP",
    //       communityCity: "Spokane Valley, WA",
    //       communityAddress: "Address",
    //       communityType: "All Ages",
    //       communityAmenities: "Amenities",
    //       communityURL: "universitymhp",
    //       communityID: "WA-1",
    //     },
    //   ],
    // },
    {
      state: "West Virginia",
      usStateId: "westvirginia",
      stateAbbr: "WV",
      stateBgURL: WestVirginiaShape,
      communities: [
        {
          communityName: "Cambridge MHC",
          communityCity: "Charles Town, WV",
          communityAddress: "11 Manchester Drive, Charles Town, WV",
          communityType: "All Ages",
          communityAmenities: "Amenities",
          communityURL: "cambridge",
          communityID: "WV-1",
        },
      ],
    },
  ]);
  return (
    <CommunityContext.Provider value={{ communityStates }}>
      {props.children}
    </CommunityContext.Provider>
  );
};

export default CommunityContextProvider;
